from itertools import count
list = [22,"Medicaps","Python",2.5]
list2 = [23,"Medicaps University","Python",2.5]
list3=[10,20,16,51,1,51,15,1,51,1,51,51,15,1]
print("list Numaric",list3)
print(list)
print(list2)
'''print(type(list))
print(list[3:0])
print(list[0:3])'''
print("Concated String",list+list2)
print("list before insert ",list)
list.insert(4,4)
print("list after Inserted ",list)
print("before append list",list)
list.append(10)
print("after Append in list",list)
print("before pop in list",list)
a=list.pop()
print("pop item is=" ,a)
print("after pop  list",list)
print("before remove 22 list",list)
list.remove(22)
print("after removed item in list",list)
print("befor reverse of the list",list)
b=list.reverse()
print("after reverse list:",b)
print("before sort list",list3)
list3.sort()
print("sorted list is ",list3)
list3.extend(list)
print("After extend list:",list3)
list4=list.copy()
print("copied list  in list4: ",list4)
list4.clear()
print("list4 cleared",list4)
c=list3.count(51)
print("items in list 3",c)
d=list3.index(10)
print("10 at the index :",d)

